spring:
  application:
    name: archsoft-hexagonal
  profiles:
    default: local

server:
  port: 8082

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  tracing:
    sampling:
      probability: 1.0
  otlp:
    tracing:
      endpoint: ${OTEL_EXPORTER_OTLP_TRACES_ENDPOINT:http://localhost:4318/v1/traces}
  opentelemetry:
    resource-attributes:
      service.name: archsoft-hexagonal
      archsoft.architecture: hexagonal
      archsoft.scenario: orders-mvp
      archsoft.repo: archsoft-hexagonal
      deployment.environment: local

logging:
  pattern:
    level: "%5p [requestId:%X{requestId:-} runId:%X{runId:-}]"
